/**
 * This file contains all TypeScript type definitions for the PokéMaker app.
 * These types help ensure data is structured correctly and catch errors early.
 */

// The 18 official Pokémon types
export type PokemonType =
  | 'Normal' | 'Fire' | 'Water' | 'Electric'
  | 'Grass' | 'Ice' | 'Fighting' | 'Poison'
  | 'Ground' | 'Flying' | 'Psychic' | 'Bug'
  | 'Rock' | 'Ghost' | 'Dragon' | 'Dark'
  | 'Steel' | 'Fairy';

// Evolution stages
export type EvolutionStage = 'Basic' | 'Stage 1' | 'Stage 2';

// Growth/Experience rates
export type GrowthRate =
  | 'Erratic' | 'Fast' | 'Medium Fast'
  | 'Medium Slow' | 'Slow' | 'Fluctuating';

// Egg groups for breeding
export type EggGroup =
  | 'Monster' | 'Water 1' | 'Water 2' | 'Water 3'
  | 'Bug' | 'Flying' | 'Field' | 'Fairy'
  | 'Grass' | 'Human-Like' | 'Mineral' | 'Amorphous'
  | 'Ditto' | 'Dragon' | 'Undiscovered';

// Unit types for measurements
export type HeightUnit = 'feet' | 'meters';
export type WeightUnit = 'pounds' | 'kilograms';

// Ability information
export interface Ability {
  name: string;
  description: string;
}

// EV (Effort Value) yield - which stats give EVs when defeated
export interface EVYield {
  hp?: number;
  attack?: number;
  defense?: number;
  specialAttack?: number;
  specialDefense?: number;
  speed?: number;
}

// Move learned by leveling up
export interface LevelUpMove {
  name: string;
  level: number;
}

// Complete Pokémon data structure
export interface Pokemon {
  // Database ID (generated by Supabase)
  id?: string;

  // Timestamps
  createdAt?: string;
  updatedAt?: string;

  // User ownership
  userId?: string;

  // === BASIC IDENTITY ===
  name: string;
  pokedexNumber?: number;
  category?: string; // e.g., "Seed Pokémon"
  typePrimary: PokemonType;
  typeSecondary?: PokemonType;
  color?: string;

  // === PHYSICAL CHARACTERISTICS ===
  heightValue?: number;
  heightUnit?: HeightUnit;
  weightValue?: number;
  weightUnit?: WeightUnit;
  shape?: string;
  pokedexEntry?: string; // Description text

  // === BATTLE STATS ===
  // Stats range from 1-255 (all optional)
  hp?: number;
  attack?: number;
  defense?: number;
  specialAttack?: number;
  specialDefense?: number;
  speed?: number;

  // === ABILITIES ===
  ability1?: Ability;
  ability2?: Ability;
  hiddenAbility?: Ability;

  // === EVOLUTION & BREEDING ===
  evolutionStage?: EvolutionStage;
  evolvesFrom?: string;
  evolvesInto?: string;
  evolutionMethod?: string; // e.g., "Level 16", "Fire Stone", "Trade"
  eggGroup1?: EggGroup;
  eggGroup2?: EggGroup;
  genderRatioMale?: number; // 0-100 percentage
  genderRatioFemale?: number; // 0-100 percentage
  isGenderless?: boolean;
  eggCycles?: number;

  // === GAME MECHANICS ===
  catchRate?: number; // 0-255
  baseFriendship?: number; // 0-255
  growthRate?: GrowthRate;
  evYield?: EVYield;

  // === IMAGES ===
  originalDrawingUrl?: string; // User's uploaded drawing
  aiGeneratedImageUrl?: string; // Final AI-generated image (optional - user can save without it)
  physicalAppearance?: string; // Description of physical features for AI generation
  imageDescription?: string; // Description of personality/mood for AI generation

  // === MOVES ===
  levelUpMoves?: LevelUpMove[];
  tmMoves?: string[]; // Array of TM move names
  eggMoves?: string[]; // Array of egg move names
}

// Form data used during Pokémon creation/editing
// This might differ slightly from the database structure
export interface PokemonFormData extends Omit<Pokemon, 'id' | 'createdAt' | 'updatedAt'> {
  // Additional form-specific fields can go here
}

// For displaying Pokémon in the gallery
export interface PokemonCardData {
  id: string;
  name: string;
  pokedexNumber?: number;
  typePrimary: PokemonType;
  typeSecondary?: PokemonType;
  aiGeneratedImageUrl?: string;
  originalDrawingUrl?: string; // Fallback if no AI image
}
